### ISSUE TITLE
EIPIP Meeting 2 Agenda

### ISSUE THREAD

**Issue by Souptacular** [ethereum-cat-herders/EIPIP#1]
# EIPIP Meeting 2 Agenda

-   Meeting Date/Time:  **Friday 29 January 2020, [15:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/jan-29-2020/3pm)**
-   Meeting Duration 1 hour
-   [YouTube Live Stream](https://youtu.be/oviaIsMLb8M)

# Agenda

1. Ordering the most important issues to address.
1. Dividing into teams to come up with ideas for solutions.
1. Next call

**Comment by BrentAllsop** [comment]
Is #1 on the agenda about prioritizing EIPs?  Or something else?

**Comment by poojaranjan** [comment]
Edited the date to Friday 29 January 2020. Meeting concluded.
