### ISSUE TITLE
Rename master branch to main branch

### ISSUE THREAD

**Issue by Pandapip1** [ethereum-cat-herders/EIPIP#122]
See: https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main

Issue on EIP repo (discussion / debate / vote): https://github.com/ethereum/EIPs/issues/4945

**Comment by MicahZoltu** [comment]
It would probably be best to keep the discussion in one location.  I recommend issue in EIP repository in this case as that is where EIP process change discussions tend to occur.

**Comment by poojaranjan** [comment]
@Pandapip1, Are we good to close this since it is also being discussed in another repo?

**Comment by Pandapip1** [comment]
Probably.

**Comment by Pandapip1** [comment]
Oh, I should also point out that this repo too has the main branch named `master`.
