### ISSUE TITLE
EIPIP Meeting 8 Agenda

### ISSUE THREAD

**Issue by edsonayllon** [ethereum-cat-herders/EIPIP#15]
## Date

May 20, 2020, at 15:00 UTC

## Location

Zoom: The link will be shared in the telegram group.
YouTube Recording Link: TBA

## Agenda

1. EIP centric model subgroup, next steps
2. EFI to its own EIP, referenced in EIP-1
3. [EIPIP Survey](https://docs.google.com/forms/d/e/1FAIpQLSeadXscoQgrKznUOAEB_jSzNNFKHWDEFJxKH1LpDsDsC6mXpw/viewform)
4. Making decision-making async from ACD calls
5. Separation of EIP process and hard-fork coordination
    - Axic's EIP status model 
    - <img width="348" alt="Screen Shot 2020-05-15 at 5 02 39 PM" src="https://user-images.githubusercontent.com/34966228/82099839-f1f44100-96cd-11ea-935b-b0bf4ec778f7.png">
6. [ZIPs reference](https://github.com/zcash/zips/blob/master/zip-0000.rst)
    - Keywords
7. Discuss EIP-1 Brainstorming Document.
    - Goals Outcomes
    - What we are not doing.
8. Review previous meeting

*Next Call - June 3, 2020*

**Comment by MadeofTin** [comment]
Discuss EIP-1 Brainstorming Document.
 - Goals Outcomes
 - What we are not doing.

cc: @Souptacular

**Comment by alita-moore** [comment]
- Discuss adding key words

**Comment by edsonayllon** [comment]
> * Discuss adding key words

As in from the ZIPs?

**Comment by alita-moore** [comment]
> 
> As in from the ZIPs?
yep, the use of keywords like SHOULD, MUST, etc. is a very professional and important part of proposals I've seen in the aerospace industry. I imagine that adding them would not only make the EIP process look more professional but also add clarity.

**Comment by edsonayllon** [comment]
> yep, the use of keywords like SHOULD, MUST, etc. is a very professional and important part of proposals I've seen in the aerospace industry. Adding them would not only make the EIP process look more professional but also add clarity.

Ok, already added.

**Comment by MadeofTin** [comment]
![image](https://user-images.githubusercontent.com/1226869/82463102-a816ac80-9a79-11ea-9093-cca039839897.png)
 image for reference

**Comment by poojaranjan** [comment]
Closed in favor of #16
