### ISSUE TITLE
EIPIP Meeting 65 Agenda

### ISSUE THREAD

**Issue by SamWilsn** [ethereum-cat-herders/EIPIP#176]
# Date and Time

Wednesday, Sep 21, 2022, at 14:00 UTC

# Location

Zoom: TBA in the Discord #eip-editing channel

YouTube Live Stream/Recording: https://www.youtube.com/playlist?list=PL4cwHXAawZxpLrRIkDlBjDUUrGgF91pQw

# Agenda

### 1. Discuss

 - [ ] ethereum/EIPs#5367
 - [ ] ethereum/EIPs#5596
 - [ ] ethereum/EIPs#5502
 - [ ] `execution-specs`
 
Issues
 - [ ] https://github.com/ethereum/EIPs/issues/5682
 - [ ] https://github.com/ethereum/EIPs/issues/5662
 - [ ] https://github.com/ethereum/EIPs/issues/5652
 - [ ] https://github.com/ethereum/EIPs/issues/5651
 - [ ] https://github.com/ethereum/EIPs/issues/5641

### 2. Past meeting discussion continued
  - what license to use for EIP assets

### 5. [EIP Editing Office Hour](https://hackmd.io/@poojaranjan/EIPEditingOfficeHour)
- Meeting 2 [Recording](https://youtu.be/YAKJDxBkItg) & [Agenda Meeting 3](#180)

### 6. Review action items from the previous meeting
- EIP number bot (Ref: [Issue](https://github.com/ethereum/EIP-Bot/issues/64))
- Prev. meeting [notes](https://github.com/ethereum-cat-herders/EIPIP/blob/dda5b4c7474d738efed4bc9bfe8ab69953e3d914/All%20EIPIP%20Meetings/Meeting%20064.md) 

**Next meeting** - Oct 5, 2022

**Comment by Pandapip1** [comment]
https://github.com/ethereum/EIPs/pull/5596
https://github.com/ethereum/EIPs/pull/5576
https://github.com/ethereum/EIPs/pull/5696
https://github.com/ethereum/EIPs/pull/5680
https://github.com/ethereum/EIPs/pull/5655
https://github.com/ethereum/EIPs/pull/5619
https://github.com/ethereum/EIPs/pull/5361
https://github.com/ethereum/EIPs/pull/5508

I'll be late by 30+ minutes.

**Comment by Pandapip1** [comment]
@SamWilsn I don't have access to discord rn. Mind giving the zoom link?

**Comment by poojaranjan** [comment]
https://us02web.zoom.us/j/82357016731?pwd=V0hLUWIvU2V2UTdUd216WHdGNFBKUT09

**Comment by poojaranjan** [comment]
Closing in favor of #181
