### ISSUE TITLE
EIPIP Meeting 71 Agenda

### ISSUE THREAD

**Issue by dtedesco1** [ethereum-cat-herders/EIPIP#198]
# Date and Time
Wednesday, Dec 14, 2022, at 15:00 UTC

# Location
Zoom: TBA in the Discord #eip-editing channel

YouTube Live Stream/Recording: https://www.youtube.com/playlist?list=PL4cwHXAawZxpLrRIkDlBjDUUrGgF91pQw

# Agenda

### 1. Discuss Issues/PRs, topics
- [x] https://github.com/ethereum/EIPs/issues/6129
- [x] https://github.com/ethereum/EIPs/issues/6027

Changes to `Final` EIP
- [x] https://github.com/ethereum/EIPs/pull/6104
- [x] https://github.com/ethereum/EIPs/pull/6038
- [x] https://github.com/ethereum/EIPs/pull/6012
- [x] https://github.com/ethereum/EIPs/pull/5877

### 2. Discussion continued from earlier meetings
- [x] Discussion of Criteria for advancing EIP status: [A Straw-man Proposal](https://ethereum-magicians.org/t/discussion-of-criteria-for-advancing-eip-status-a-straw-man-proposal/11995/1)
  - [ ] https://github.com/ethereum/EIPs/commits/master/EIPS/eip-6049.md
- [ ] https://github.com/ethereum/EIPs/pull/5789

### 3. EIP Bot
- [x] https://github.com/ethereum/EIPs/issues/6131

### 4. EIPs Insight - Monthly EIPs status reporting.
[EIPsInsight.com](https://eipsinsight.com/december-2022)
[Hackmd](https://hackmd.io/@poojaranjan/EthereumImprovementProposalsInsight/)

### 5. [EIP Editing Office Hour](https://hackmd.io/@poojaranjan/EIPEditingOfficeHour)
Recording [Meeting 8](https://youtube.com/live/NNlz0oEupfE?feature=share)
Agenda [Meeting 9](https://github.com/ethereum-cat-herders/EIPIP/issues/201)

### 6. Review action items from earlier meetings
Prev. meeting [notes 70](https://github.com/ethereum-cat-herders/EIPIP/blob/master/All%20EIPIP%20Meetings/Meeting%20070.md)

Next meeting - _TBD_

**Comment by xinbenlv** [comment]
Procedure disuccsion https://ethereum-magicians.org/

**Comment by poojaranjan** [comment]
### Summary

1. Discuss Issues/PRs, topics
- Propose Policy: Last Call changes shall be separate from the PR to move to Final 
**Decision**: Big changes in `Last Call` will restart the "Review ends" date
- Hide Stagnant and Withdrawn EIPs from the EIP list 
**General consensus**: Not very useful feature to hide

Changes to Final EIP

-  PR-6104: Sam will merge it
- PR-6038: General consensus - PR should not be merged. Sam will create an issue for concern regarding updating Solidity to old EIPs.
- PR-6012: Author needs to list normative changes and non-normative changes. We should avoid adding change to big EIPs like this. Closed.
 - PR-5877: Shouldn't change older EIPs for updating table. Anyway, an EIP isn't a best place to maintain a table.
 
2. Discussion continued from earlier meetings
- A Straw-man Proposal: Continue collecting feedback [here](https://ethereum-magicians.org/t/discussion-of-criteria-for-advancing-eip-status-a-straw-man-proposal/11995/10)

3. EIP Bot
- Group seems to be in favor. Will keep the issue to collect if anyone opposes to the proposal.

**Comment by poojaranjan** [comment]
Closing in favor of #202
