### ISSUE TITLE
EIP-5851 didn't get it auto merged.

### ISSUE THREAD

**Issue by Jooeys** [ethereum-cat-herders/EIPIP#206]
Dear editor @poojaranjan  please check this PR https://github.com/ethereum/EIPs/pull/5851, since it's been a very long time waiting for this EIP to move to draft status after we have completed all the patches suggested by editors. Best, Joey

**Comment by poojaranjan** [comment]
I hope it is merged before the next Office hour, yet, added to the next meeting's agenda. #204

**Comment by Pandapip1** [comment]
There appear to still be outstanding concerns. Have all of these been addressed?

**Comment by poojaranjan** [comment]
The PR was discussed in meeting #204. Thanks team for joining. Feel free to share issues if any on ECH Discord #eip-editors

**Comment by poojaranjan** [comment]
Merged!
