### ISSUE TITLE
Agenda request: PR #6483

### ISSUE THREAD

**Issue by fulldecent** [ethereum-cat-herders/EIPIP#215]
Requesting a review please of https://github.com/ethereum/EIPs/pull/6483

This includes several changes furthering the goal of making EIPs useful, and keeping the community together rather than immediately splitting off several EIP groups with their own independent leadership and processes.

_(Note that maybe EIPs will be split out, and maybe that is a good thing. Or not. But this is PR addresses immediate problems.)_

1. EIP website is focused on EIPs (currently it is focused on classifications and instructions, boring)
2. The EIP website gets filters, which can quickly show you want you want to see
3. RSS feeds are added, addressing a major concern people have about getting inundated with ERC notifications

---

I am requesting please a review of this PR as a whole as-is without modification as to whether it is a net improvement and whether it should be merged now.

Requesting this feedback on that PR as available---and then as necessary (if not merged) at the next EIPIP meeting.

If such consensus cannot be made to merge the PR as-is, I am alternatively requesting a review of the three specific initiatives above and a commitment to merge (with sufficient quorum/authority) if such a small refactoring of #6483 shall be made.

**Comment by Pandapip1** [comment]
Again, I am blocking this PR until 1/2 is split from 3.

**Comment by Pandapip1** [comment]
@fulldecent would you mind looking at my rewrite? https://github.com/ethereum/EIPs/pull/6518

I believe this solves your use cases.

**Comment by fulldecent** [comment]
Thank you for sharing. As for https://github.com/ethereum/EIPs/pull/6518 I left a few notes here.

My concerns in this PR are not addressed by that alternate PR.

Specifically, https://github.com/ethereum/EIPs/pull/6483 addresses the main concern than "ERCs are too noisy". It solves that by making filtering an immediate feature of the website.

**Comment by Pandapip1** [comment]
> Specifically, ethereum/EIPs#6483 addresses the main concern than "ERCs are too noisy". It solves that by making filtering an immediate feature of the website.

Have you tried https://eips.pandapip1.com/search? It supports filtering:

https://eips.pandapip1.com/search?search=category%3ACore+status%3AReview+selfdestruct

**Comment by fulldecent** [comment]
On that I do not see a button here for filtering:

<img width="1411" alt="Screenshot 2023-02-24 at 17 45 19" src="https://user-images.githubusercontent.com/382183/221311787-5ec08298-77b8-42a3-bb6d-c83786f57c83.png">

---

Compared to the other, the button is front and center on the homepage

![image](https://user-images.githubusercontent.com/382183/221312063-d54d79c8-d28e-4062-85b0-4b4e974d6b09.png)

(this screenshot is shown in light mode and rest assured that website also works in dark mode)

**Comment by Pandapip1** [comment]
Fair enough. I'll add a filter button. Also, it's not buried:

![Screenshot 2023-02-24 201507](https://user-images.githubusercontent.com/45835846/221327943-ffcf8470-64e4-4a8e-926c-3f5bb0f6c628.png)

(Also, what browser is that? It looks cool!)

**Comment by fulldecent** [comment]
That's Arc. I'll send you an invite code, just DM me @fulldecent or email me. Warning that there is an EXTREME amount of phone-homes which you can block with Little Snitch or similar.

That screenshot is showing search and browse links to show content. The other PR https://github.com/ethereum/EIPs/pull/6483 requires zero clicking and uses the well-known CTRL-F for search. So relatively, the other PR is burried.

**Comment by Pandapip1** [comment]
> That screenshot is showing search and browse links to show content. The other PR ethereum/EIPs#6483 requires zero clicking and uses the well-known CTRL-F for search. So relatively, the other PR is burried.

The other PR uses the `K` key to open the search page, so the keybind is not relevant here. Additionally, it *does* need clicking to use the filters, while mine does not.
