### ISSUE TITLE
Funding for EIPIP Meeting 076

### ISSUE THREAD

**Issue by Avishek041180** [ethereum-cat-herders/EIPIP#221]
- PR:[EIPIP Meeting 076](https://github.com/ethereum-cat-herders/EIPIP/pull/220)

![image](https://user-images.githubusercontent.com/74140118/226205686-48600997-f00e-4706-ba0d-257a28f014d8.png)

![image](https://user-images.githubusercontent.com/74140118/226205718-cd6dd37b-0620-4373-b995-0ee4f77105ca.png)

- Amount: 100/1827.66 = 0.05471 ETH
- Wallet: 0x49053f8D0A0b56e322842D5226FB0Fe7620AE2fC

**Comment by poojaranjan** [comment]
Please create the request at the Funding repo
