### ISSUE TITLE
Call for Input: First Keeper of Consensus Election

### ISSUE THREAD

**Issue by SamWilsn** [ethereum-cat-herders/EIPIP#263]
<table>
<tr>
<th>Decision</th>
<td>Which EIP Editor should be our first Keeper of Consensus?</td>
</tr>
<tr>
<th>Method</th>
<td>Vote</td>
</tr>
<tr>
<th>Deadline</th>
<td>October 6, 2023</td>
</tr>
</table>

**Comment by SamWilsn** [comment]
I vote for @g11tech

**Comment by Pandapip1** [comment]
I vote for @SamWilsn

**Comment by xinbenlv** [comment]
Vote for @SamWilsn.

@SamWilsn  doesn't shy away from sharing his views but also makes great effort to harness opinions of diverse views from EIP editors and broader EIP contributor community. When he held minority view on an issue, he demonstrated the judgement of different hat he wears: as a opinion holder and as a role of trust in the community. He did well interpreting and exercising the consensus even when it didnt side with his. I vote for him

**Comment by Pandapip1** [comment]
To speed up this process, I request that @SamWilsn vote for himself.

**Comment by SamWilsn** [comment]
> To speed up this process, I ask that @SamWilsn vote for himself, which will give a majority.

Majority or not, quorum is only met once everyone has voted or 30 days has elapsed.

**Comment by Pandapip1** [comment]
Fair enough

**Comment by lightclient** [comment]
I vote for Sam

**Comment by Pandapip1** [comment]
The deadline has passed, and so the quorum has been reduced to the editors that have voted, and has therefore been met. @SamWilsn has the most votes.

**Comment by poojaranjan** [comment]
Closed in favor of @SamWilsn to be the [First Keeper of Consensus Election](https://github.com/ethereum-cat-herders/EIPIP/issues/263#top)
