### ISSUE TITLE
Call for Input: Editor Removal (@lightclient)

### ISSUE THREAD

**Issue by SamWilsn** [ethereum-cat-herders/EIPIP#265]
<table>
<tr>
<th>Decision</th>
<td>Will we remove @lightclient as an EIP Editor?</td>
</tr>
<tr>
<th>Method</th>
<td>Unanimous (minus the Editor being removed)</td>
</tr>
<tr>
<th>Deadline</th>
<td>October 6, 2023</td>
</tr>
</table>

**Comment by SamWilsn** [comment]
In the interest of not having to wait the full 30 days, I am giving my opinion. Since I'm proposing these rather... rude calls for input, I'm going to abstain from all of them.

---

**abstain**.

**Comment by Pandapip1** [comment]
I vote no.

**Comment by xinbenlv** [comment]
*oppose*. @lightclient is a valuable member of EIP editor group with his contribution, leadership and active involvement in EIP governance. he connect and empower Core developers and make their voice heard in EIP process.

**Comment by Pandapip1** [comment]
The deadline has passed, and the required votes have not been met. This can be closed.

**Comment by poojaranjan** [comment]
The proposal could not receive the required votes. @lightclient will continue to be an EIP Editor.
