### ISSUE TITLE
Call for Input: Editor Removal (@axic)

### ISSUE THREAD

**Issue by SamWilsn** [ethereum-cat-herders/EIPIP#266]
<table>
<tr>
<th>Decision</th>
<td>Will we remove @axic as an EIP Editor?</td>
</tr>
<tr>
<th>Method</th>
<td>Unanimous (minus the Editor being removed)</td>
</tr>
<tr>
<th>Deadline</th>
<td>October 6, 2023</td>
</tr>
</table>

**Comment by SamWilsn** [comment]
In the interest of not having to wait the full 30 days, I am giving my opinion. Since I'm proposing these rather... rude calls for input, I'm going to abstain from all of them.

---

**abstain**.

**Comment by Pandapip1** [comment]
I vote no.

**Comment by SamWilsn** [comment]
> I vote no.

@Pandapip1 may I ask why?

**Comment by Pandapip1** [comment]
@axic has a unique perspective. I find having a lot of different perspectives to be valuable, even though it necessarily slows down the process.

**Comment by SamWilsn** [comment]
I 100% value his contributions, but if he doesn't express his opinions on EIP governance related topics, I don't see why we should hold up every formal decision for 30 days.

**Comment by Pandapip1** [comment]
@SamWilsn convinced me to change. My vote is a "yes" if @axic has not responded by the deadline, a "no" as soon as he does respond, and an "abstain" in the meantime.

**Comment by g11tech** [comment]
> I 100% value his contributions, but if he doesn't express his opinions on EIP governance related topics, I don't see why we should hold up every formal decision for 30 days.

+1 , would also support re-join

**Comment by Pandapip1** [comment]
My vote has now been updated to a **"YES"**, until @axic responds before the CFI deadline.

**Comment by axic** [comment]
I'd like to stay, even if the environment has been adversarial causing in a decline of my motivation, I do hope to contribute in the near future.

**Comment by lightclient** [comment]
As long as @axic plans to stick around, I would like to support him as an editor.

**Comment by Pandapip1** [comment]
@axic I will change my vote to a "No." As per the most EIPIP meeting, we highly recommend you to delegate the voting power to either another editor or to an "abstain by default" social contract.

**Comment by g11tech** [comment]
changing vote to `No` as well

**Comment by lightclient** [comment]
no

**Comment by xinbenlv** [comment]
axic, you have authored many important EIPs and reviewed/edited many. Your skills and experience is a great asset to the group. While I understand you are driving a lot of time sensitive core development at the moment, if you could commit to stay and resume EIP editing soon I would personally be very supportive you stay.

**Comment by Pandapip1** [comment]
The deadline has passed, and the required votes have not been met. This can be closed.

**Comment by poojaranjan** [comment]
The proposal could not receive the required votes. @axic will continue to be an EIP Editor.
