### ISSUE TITLE
Call for Input: Editor Removal (@pandapip1)

### ISSUE THREAD

**Issue by SamWilsn** [ethereum-cat-herders/EIPIP#268]
<table>
<tr>
<th>Decision</th>
<td>Will we remove @pandapip1 as an EIP Editor?</td>
</tr>
<tr>
<th>Method</th>
<td>Unanimous (minus the Editor being removed)</td>
</tr>
<tr>
<th>Deadline</th>
<td>October 6, 2023</td>
</tr>
</table>

**Comment by SamWilsn** [comment]
In the interest of not having to wait the full 30 days, I am giving my opinion. Since I'm proposing these rather... rude calls for input, I'm going to abstain from all of them.

---

**abstain**.

**Comment by Pandapip1** [comment]
I mean, I'll obviously vote no to this one.

**Comment by g11tech** [comment]
i oppose the motion :slightly_smiling_face: :heart:

**Comment by xinbenlv** [comment]
*oppose*: @Pandapip1 is a valuable member of EIP Editor group who actively edits ERCs and EIPs and has been the key contributor of website and the repo CI tools.

**Comment by lightclient** [comment]
no

**Comment by Pandapip1** [comment]
The deadline has passed, and the required votes have not been met. This can be closed.

**Comment by poojaranjan** [comment]
The proposal could not receive the required votes. @Pandapip1  will continue to be an EIP Editor.
