### ISSUE TITLE
Call for Input: Editor Removal (@g11tech)

### ISSUE THREAD

**Issue by SamWilsn** [ethereum-cat-herders/EIPIP#269]
<table>
<tr>
<th>Decision</th>
<td>Will we remove @g11tech as an EIP Editor?</td>
</tr>
<tr>
<th>Method</th>
<td>Unanimous (minus the Editor being removed)</td>
</tr>
<tr>
<th>Deadline</th>
<td>October 6, 2023</td>
</tr>
</table>

**Comment by SamWilsn** [comment]
In the interest of not having to wait the full 30 days, I am giving my opinion. Since I'm proposing these rather... rude calls for input, I'm going to abstain from all of them.

---

**abstain**.

**Comment by Pandapip1** [comment]
I vote no.

**Comment by xinbenlv** [comment]
*oppose*: @g11tech provides valuable perspective from Core Devs, an active Editor help editing EIPs

**Comment by lightclient** [comment]
no

**Comment by Pandapip1** [comment]
The deadline has passed, and the required votes have not been met. This can be closed.
