### ISSUE TITLE
Call for Input: Allow links to CVEs

### ISSUE THREAD

**Issue by SamWilsn** [ethereum-cat-herders/EIPIP#273]
<table>
    <tr>
        <th>Decision</th>
        <td>Merge ethereum/EIPs#7542</td>
    </tr>
    <tr>
        <th>Method</th>
        <td>Rough Consensus</td>
    </tr>
    <tr>
        <th>Deadline</th>
        <td>2023-10-05</td>
    </tr>
</table>

**Comment by Pandapip1** [comment]
I vote yes.

**Comment by SamWilsn** [comment]
I think we can probably allow these. I'm not a fan of having to use dates to specify versions, but c'est la vie.

**Comment by xinbenlv** [comment]
In favor of allowing links to CVE.

**Comment by SamWilsn** [comment]
Consensus is to allow links to CVEs.
