### ISSUE TITLE
Call for Input: Renumber EIP-5000

### ISSUE THREAD

**Issue by SamWilsn** [ethereum-cat-herders/EIPIP#274]
<table>
<tr>
<th>Decision</th>
<td>

Will we merge https://github.com/ethereum/EIPs/pull/5270 ?

</td>
</tr>
<tr>
<th>Method</th>
<td>Rough Consensus</td>
</tr>
<tr>
<th>Deadline</th>
<td>October 13, 2023</td>
</tr>
</table>

**Comment by Pandapip1** [comment]
-0.9 (**Vote: "NO"**)or reasons previously stated.

**Comment by g11tech** [comment]
+1, reasoning: broken window (https://en.wikipedia.org/wiki/Broken_windows_theory)

**Comment by xinbenlv** [comment]
+1, I left my comment in original PR https://github.com/ethereum/EIPs/pull/5270 and I continue to hold that view until otherwise convinced.

**Comment by lightclient** [comment]
@g11tech the "broken window theory" isn't very good reasoning for renumbering this because assigning the number 5000 wasn't a "crime". You don't make something illegal and then go back and prosecute people who broke the law before it was a law.

**Comment by abcoathup** [comment]
No (but I don't have a vote). EIP editors shouldn't force a renumber, though I encourage the authors to seek a new number.
Whilst the numbering is unfair, it wasn't against the rules in EIP-1
https://github.com/ethereum/EIPs/pull/5270#issuecomment-1689249709

**Comment by xinbenlv** [comment]
Thanks for clarifying. I do agree the author shall seek a different number themselves first, and maybe different from you, in the event the author is not responding i think editors are held higher standards in event of doubt and for that rational I support merging the PR of renumbering

**Comment by SamWilsn** [comment]
I am in favour of renumbering.

**Comment by SamWilsn** [comment]
From @gcolvin:

> Just let it go, why are we wasting time on this. It wasn't against the rules at the time.

**Comment by SamWilsn** [comment]
Official Keeper of Consensus ruling: consensus is to not renumber.
