### ISSUE TITLE
Call for Input: Allow links to the Yellow Paper

### ISSUE THREAD

**Issue by SamWilsn** [ethereum-cat-herders/EIPIP#275]
<table>
<tr>
<th>Decision</th>
<td>

Will we merge https://github.com/ethereum/EIPs/pull/6834 ?

</td>
</tr>
<tr>
<th>Method</th>
<td>Rough Consensus</td>
</tr>
<tr>
<th>Deadline</th>
<td>October 13, 2023</td>
</tr>
</table>

**Comment by Pandapip1** [comment]
I vote yes. It's a free source and the commits are immutable.

**Comment by SamWilsn** [comment]
I am also in favour of allowing links to the Yellow Paper. It meets the requirements in EIP-5757.

**Comment by Pandapip1** [comment]
Nonetheless, it meets the requirements set by EIP-5757. Also, I believe maintaining the Yellow Paper is valuable.

**Comment by SamWilsn** [comment]
From @gcolvin:

> Allow links.

From @xinbenlv:

> Allow links.

**Comment by SamWilsn** [comment]
https://github.com/ethereum/EIPs/pull/7884
