### ISSUE TITLE
Call for Input: Updating EIP-4804 (Web3 URLs)

### ISSUE THREAD

**Issue by SamWilsn** [ethereum-cat-herders/EIPIP#276]
<table>
<tr>
<th>Decision</th>
<td>

Will we merge https://github.com/ethereum/EIPs/pull/6860 ?

</td>
</tr>
<tr>
<th>Method</th>
<td>Rough Consensus</td>
</tr>
<tr>
<th>Deadline</th>
<td>October 13, 2023</td>
</tr>
</table>

**Comment by poojaranjan** [comment]
No consensus, ref [summary](https://github.com/ethereum-cat-herders/EIPIP/issues/281#issuecomment-1768740036).
