### ISSUE TITLE
Call for Input: Accidental function in ERC-223

### ISSUE THREAD

**Issue by SamWilsn** [ethereum-cat-herders/EIPIP#283]
<table>
<tr>
<th>Decision</th>
<td>

Will we merge https://github.com/ethereum/EIPs/pull/7856? See that pull request for details.

</td>
</tr>
<tr>
<th>Method</th>
<td>Rough Consensus</td>
</tr>
<tr>
<th>Deadline</th>
<td>November 16, 2023</td>
</tr>
</table>

tl;dr function was removed from spec then later accidentally re-added.

**Comment by SamWilsn** [comment]
I don't see a problem with this. Like @Pandapip1 says, removing this function is backwards compatible and this definitely looks like a mistake on the authors' part.

---

**merge**

**Comment by Pandapip1** [comment]
+1 for me. Will also assist @Dexaran if he wants to seperate this into its own standard as-is.

**Comment by xinbenlv** [comment]
I thought the ERC-223 is... final?

**Comment by g11tech** [comment]
i am fine removing something which accidentally got by and already notifies in EIP that implementations shouldn't depend on it

**Comment by xinbenlv** [comment]
I am fine to have it removed if it's accidental inclusion provided it's still very close. And let's avoid this next time.
