### ISSUE TITLE
Call for Input: Ratify Editors Listed in EIP-1

### ISSUE THREAD

**Issue by SamWilsn** [ethereum-cat-herders/EIPIP#286]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we recognize the EIP Editors in EIP-1 as the current set of EIP Editors?

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>The editor list in EIP-1 (including @g11tech and @xinbenlv) becomes the official list.</td>
</tr>
<tr>
<th>If Rejected</th>
<td>@g11tech and @xinbenlv are removed from the editor list in EIP-1 and the modified list becomes the official list.</td>
</tr>
<tr>
<th>Method</th>
<td>Unanimous</td>
</tr>
<tr>
<th>Deadline</th>
<td>November 19, 2023</td>
</tr>
</table>

## Background

@xinbenlv and @g11tech are listed as EIP Editors in EIP-1, but there is some question as to whether they are "EIP Editors" in the [EIP-5069](https://eips.ethereum.org/EIPS/eip-5069) sense. Since this came up on the last EIPIP call, I would like to settle this matter officially.

I am opening this Call for Input as "Unanimous" because this is akin to adding a new editor.

**Comment by SamWilsn** [comment]
I am **in favour** of recognizing the current list.

**Comment by abcoathup** [comment]
+1 (voting as an associate)

**Comment by SamWilsn** [comment]
Since the deadline has elapsed, and all respondents are in favour, @g11tech and @xinbenlv are officially recognized as Editors :tada:
