### ISSUE TITLE
Call for Input: Withdraw EIP-7199

### ISSUE THREAD

**Issue by SamWilsn** [ethereum-cat-herders/EIPIP#289]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we merge https://github.com/ethereum/EIPs/pull/7225?

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

https://github.com/ethereum/EIPs/pull/7225 is merged, changing EIP-7199 to Withdrawn.

</td>
</tr>
<tr>
<th>If Rejected</th>
<td>EIP-7199 continues the regular flow for EIPs</td>
</tr>
<tr>
<th>Method</th>
<td>Rough Consensus</td>
</tr>
<tr>
<th>Deadline</th>
<td>November 14, 2023</td>
</tr>
</table>

**Comment by SamWilsn** [comment]
I am **in favour** of withdrawing EIP-7199.

---

If we want to add the rule it proposes, it should be added to EIP-1.

**Comment by g11tech** [comment]
+1 for the reasons that EIP-1 should be self contained

**Comment by SamWilsn** [comment]
Merging and closing.
