### ISSUE TITLE
EIP Bot Requirements

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/EIPIP#59]
The bot is in [its final stages](https://github.com/ethereum/EIPs/pull/3351) of being transferred to github / typescript and is now much more scallable in its infrastructure. There was talk of more features that are wanted from the group, so I want to put together a requirements document that plans that out. What features would you like to see for the bot? @MicahZoltu @lightclient @Souptacular

**Comment by MicahZoltu** [comment]
For starters: Validate the metadata has all of the required sections filled out correctly.  For example, `discussions-to` must be present and it must point either to an https://ethereum-magicians.org/ thread or a GitHub issue in the EIPs repository.

**Comment by MicahZoltu** [comment]
🤔  Though, I suppose that should actually be part of CI, not the merge bot...

**Comment by MicahZoltu** [comment]
Auto-merge if an author of an EIP is adding files to `../assets/eip-xxx/*`.  Right now the bot blocks because files are being added outside of the `EIPS` folder, but authors should be able to freely add/edit files in their EIP's assets folder.

**Comment by MicahZoltu** [comment]
Merge bot should auto-merge if the author wants to change from Draft, Review, or Last Call to Withdrawn.  This should include if the author approves a pull request to do such a move as well.

Example: https://github.com/ethereum/EIPs/pull/3406 should have auto-merged when the author approved.

**Comment by alita-moore** [comment]
From Micah

Also, (added feature, doesn't exist in legacy bot): if an editor review is required (because it is changing status) require an editor to approve the PR as well as either the author of the PR be an author of the EIP or an author of the EIP has approved the PR.

**Comment by alita-moore** [comment]
The bot was recently made live, this can be closed. I will continue to support its integration and to improve it along with my other work with the ECH engineering stipend.
