### ISSUE TITLE
An additional feature for a bot needed for EIPs

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/EIPIP#73]
**Goal**: Move EIPs listed at eips.ethereum.org to the appropriate status.

**Requirement**:  The EIP bot should be able to look into the inactivity period of a proposal (at eips.etherum.org), checking the last edit or last time there's a PR for that proposal. if "inactivity" is longer than a year, then move it to “withdrawn”.

**Ref**: [EIPIP meeting 34](https://youtu.be/7pPyXnlAAjs).

If you're willing to take up this task, respond to the issue. Thanks!

**Comment by DockBoss** [comment]
I will take on this project.

**Comment by alita-moore** [comment]
I am happy to help / support in any way I can! This should be an [on schedule](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule) github actions workflow that parses through all EIPs and then makes changes accordingly.

**Comment by poojaranjan** [comment]
@DockBoss we missed you in the EIPIP meeting today, wondering if you have any update to share?

**Comment by DockBoss** [comment]
@poojaranjan I have been moving the past few days and it has taken longer than I expected. I finally got internet last night and I completely spaced the meeting. I was focusing all of my effort on JSON-RPC edge casing the week before my move. I will have time to start on it this week.

**Comment by poojaranjan** [comment]
Thanks for the update @DockBoss. Feel free to share if you have any questions.  
Can we target this to be completed before the next EIPIP meeting  (July 14, 2021)?

**Comment by DockBoss** [comment]
Yes @poojaranjan I can complete it before the 14th.

**Comment by DockBoss** [comment]
@poojaranjan  I am sorry I did not do this 11 days ago, but I am unable to complete this task. My confidence turned out to be nothing more than hubris. I will not take on projects in the future unless I am certain in my ability to do them.

**Comment by alita-moore** [comment]
I can work on this next week

**Comment by poojaranjan** [comment]
No problem @DockBoss 
We appreciate your contribution to other tasks. Thank you for your work!

**Comment by alita-moore** [comment]
@poojaranjan I implemented this here: https://github.com/ethereum/EIPs/pull/3732

**Comment by alita-moore** [comment]
the bot is live so it would be ideal if this was closed

**Comment by alita-moore** [comment]
there is follow up work that I'm doing but this issue seems to me to be initial implementation which is complete

**Comment by poojaranjan** [comment]
Thanks @alita-moore !
